rails_home: https://www.railstutorial.org/
rails_help: http://www.railstutorial.org/help
rails_book: http://www.railstutorial.org/book
rails_learnenough: https://www.learnenough.com/
rails_screencast: https://screencasts.railstutorial.org/
rails_rubyonrails: https://rubyonrails.org/
rails_micheal: http://www.michaelhartl.com/
rails_news: http://news.railstutorial.org/
rails_contact: https://www.railstutorial.org/contact
